services:
  api-gateway:
    ports:
      - "8080:8000"
    environment:
      LOG_LEVEL: INFO


  writer-service:
    restart: unless-stopped

  invetory-service:
    restart: unless-stopped

  notification-service:
    restart: unless-stopped    
