
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 5s
      retries: 5

  postgres-notification:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${NOTIFICATIONS_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${NOTIFICATIONS_DB_NAME}
    volumes:
      - pg_notification_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${NOTIFICATIONS_DB_USER} -d ${NOTIFICATIONS_DB_NAME}"]
      interval: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  api-gateway:
    build: ./api-gateway
    env_file: ${ENV_FILE:-.env.dev}
    depends_on:
      redis:
        condition: service_healthy
      writer-service:
        condition: service_started

  writer-service:
    build: ./writer-service
    env_file: ${ENV_FILE:-.env.dev}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory-service:
    build: ./inventory-service
    restart: unless-stopped
    env_file: ${ENV_FILE:-.env.dev}
    depends_on:
      - rabbitmq

  analytics-service:
    build: ./analytics-service
    env_file: ${ENV_FILE:-.env.dev}
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  notification-service:
    build: ./notification-service
    env_file: ${ENV_FILE:-.env.dev}
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - postgres-notification
      
volumes:
  pg_data:
  pg_notification_data:
