name: CI                        # Nombre del workflow

on: [push, pull_request]        # Eventos que disparan workflow

jobs: 
    test:                       # Nombre del job
        runs-on: ubuntu-latest  # Runner (maquina virtual) donde se ejecutara el job
        steps:
            - uses: actions/checkout@v4     # Paso 1: Clonar el repositorio
            - run: echo "Hola mundo CI"     # PAso 2: Ejecutar el comando echo
            